### ISSUE TITLE
Menu bar settings not exactly working - can't hide MFC icon & more

### ISSUE THREAD

**Issue by robni7** [crystalidea/macs-fan-control#219]
When selecting to show no icon, a sensor (I choose CPU) and Exhaust, the fan speed does not display at first. Selecting none and then selecting the Exhaust again shows speed, temp and the MFC icon. However, when setting the icon dropdown to "none", the icon stays but the fan speed disappears. See screen shot. Version 1.5

Hope you an solve this :) regards

![Schermafbeelding 2019-10-06 om 03 04 36](https://user-images.githubusercontent.com/45372858/66262751-46097f80-e7e7-11e9-8e3a-eb9e16d9dc5c.png)

LOG:

> Macs Fan Control 1.5.0 [Qt 5.6.3]
> 
> MacBookAir2,1
> CPU: Intel(R) Core(TM)2 Duo CPU L9400 @ 1.86GHz [2 cores]
> GPU: NVIDIA GeForce 9400M
> macOS 10.11.6
> 
> Fans:
> Exhaust-min{2500}curr{6179}max{6200}mode{2,TC0D,50,70}
> 
> 
> TempSensors:
> TB0T () - 129, 129
> TB1S () - 0, 0
> TB1T () - 0, 0
> TB2S () - 0, 0
> TB2T () - 0, 0
> TC0D (CPU Diode) - 66.5, 66.5
> TN0D (MCP Diode) - 68.75, 68.75
> TTF0 () - 57.125, 57.125
> TV0P (AIR Vent Exit) - 58.75, 58.75
> TVFP () - 59.2852, 59.2852
> TW0P (Airport Card) - 48.5, 48.5
> Th0P () - 60.375, 60.375
> Tp0P (Power Supply Proximity) - 59.125, 59.125
> Tp1P (MLB Front Edge) - 53.25, 53.25
> TpFP () - 53.5156, 53.5156
> Ts0P (Temperature Skin Proximity) - 32.6875, 32.6875
> Ts0S () - 45.9531, 45.9531
> 
> 
> Disk drives:
> APPLE SSD SM128 - 0
> 
> Path: /Applications/Macs Fan Control.app/Contents/MacOS/Macs Fan Control

**Comment by WilliamIsted** [comment]
Can confirm the same issue I am experiencing. The 'Menubar display' > Icon field is seemingly mapped to 'Menubar display' > Fan field.

When selecting 'None' from the Icon field, this hides the Fan info, but does not change the Icon.
When selecting the 'Show' or 'Show (black & white)' via Icon this corresponds to the first and second items within the Fan field. This is verifiable by watching the corresponding fan speed change when selecting the Icon field.

[Macs Fan Control 1.5.0 [Qt 5.6.3].log](https://github.com/crystalidea/macs-fan-control/files/3755845/Macs.Fan.Control.1.5.0.Qt.5.6.3.log)

**Comment by dbgitter** [comment]
I have this issue also with Mac OS Catalina 10.15 (19A602).  In the Menubar display window, Clicking on Fan shows a checkmark briefly, but then it goes away when something else is selected. This happens intermittently and does eventually work if a certain sequence is followed.

**Comment by kleuter** [comment]
Must be fixed in the [latest beta](https://github.com/crystalidea/macs-fan-control/issues/218)

**Comment by kleuter** [comment]
fixed in 1.5.1

**Comment by s3hMC** [comment]
I'm above version 1.5.1 and I still have this issue @kleuter
