### ISSUE TITLE
Issue with following system theme on MacOS Catalina

### ISSUE THREAD

**Issue by vbuberen** [crystalidea/macs-fan-control#271]
<img width="816" alt="Screenshot 2020-01-23 at 17 10 32" src="https://user-images.githubusercontent.com/13467769/72996402-54fe5700-3e03-11ea-90c6-ee9f3d8c9d58.png">

On the latest app version (1.5.4) the color of fan icon has troubles with following `Auto` theme in Catalina on MacBook Pro 16. 
Only app restart fixes the issue.

Attaching screenshots of the issue and from both MacFanControl and MacOS settings.

Steps to reproduce:
1. Set MacOS theme to `Auto`.
2. Use MacFanControl in the evening when dark theme is active on the device.
3. Shut down the device (not `Sleep`, but `Shutdown`) when it still uses dark theme.
4. Start the device in the morning when systems starts with light theme.

<img width="102" alt="Screenshot 2020-01-23 at 10 37 26" src="https://user-images.githubusercontent.com/13467769/72968727-c2db5c00-3dcc-11ea-8668-03bed67c1acf.png">
<img width="102" alt="Screenshot 2020-01-23 at 10 37 30" src="https://user-images.githubusercontent.com/13467769/72968733-c53db600-3dcc-11ea-81c8-346eacd81115.png">
<img width="95" alt="Screenshot 2020-01-23 at 17 02 37" src="https://user-images.githubusercontent.com/13467769/72995793-2f248280-3e02-11ea-9df6-18abf86deee2.png">
<img width="100" alt="Screenshot 2020-01-23 at 17 03 05" src="https://user-images.githubusercontent.com/13467769/72995830-3f3c6200-3e02-11ea-9b22-7055127492f8.png">

<img width="449" alt="Screenshot 2020-01-23 at 10 37 43" src="https://user-images.githubusercontent.com/13467769/72968738-c7077980-3dcc-11ea-96ca-52535d3a1c92.png">
<img width="355" alt="Screenshot 2020-01-23 at 17 01 07" src="https://user-images.githubusercontent.com/13467769/72995712-0c926980-3e02-11ea-8fe8-7eca119198d7.png">

**Comment by kleuter** [comment]
One more report:

> Hello. I'm a user of the free version of MacsFanControl and I'm constantly struggling with the fact that it doesn't sync with Dark mode. 
> 
> I keep the computer running for days and I have enabled Automatic Dark Mode, and after a cycle or two, the app gets completely out of sync with the system's color.
> 
> Screenshot attached. The third, invisible icon is MacsFanControl.
> 
> 

![image](https://user-images.githubusercontent.com/2600624/75607049-74b82780-5af3-11ea-8198-e4387103f13e.png)

**Comment by kleuter** [comment]
Please try [this build](https://www.crystalidea.com/downloads/macsfancontrol_dark_test.zip)

**Comment by vbuberen** [comment]
I will install today in the evening. Will let you know as soon as I see results. I suppose that tomorrow I should already see if it works.

**Comment by vbuberen** [comment]
I was able to check both evening switch from light to dark theme and morning switch from dark to light. Both worked well on the build you provided.

**Comment by kleuter** [comment]
Thanks a lot, a new version with the fix will be released soon

**Comment by vbuberen** [comment]
@kleuter Just got this issue again. I am on this test build you provided a few days ago.
<img width="66" alt="Screenshot 2020-03-05 at 21 38 43" src="https://user-images.githubusercontent.com/13467769/76019092-e0522880-5f29-11ea-8699-ad69c65cd6ca.png">

**Comment by vbuberen** [comment]
After switching back to light theme today the icon reverted again and still has invalid color
<img width="71" alt="Screenshot 2020-03-06 at 12 30 03" src="https://user-images.githubusercontent.com/13467769/76075772-42507380-5fa6-11ea-8648-11e91ccc8d29.png">

**Comment by kleuter** [comment]
Please check [this build](https://www.crystalidea.com/downloads/macsfancontrol_dark_test_2.zip), must work now!

**Comment by vbuberen** [comment]
Ok, trying it out.

**Comment by vbuberen** [comment]
> Please check [this build](https://www.crystalidea.com/downloads/macsfancontrol_dark_test_2.zip), must work now!

After running the test for a few days I can confirm that everything works fine.
Both `Shut down` and `Sleep` cause no issues for system theme following.

**Comment by kleuter** [comment]
thanks a lot, great!

**Comment by sebolio** [comment]
Why are you handling the icon manually? the OS changes it to white automatically if it's black

**Comment by kleuter** [comment]
Because we don't use template images at the moment.

**Comment by kleuter** [comment]
Fixed in 1.5.5

**Comment by kleuter** [comment]
It's finally fixed in 1.5.5.17 (not 16)

**Comment by vbuberen** [comment]
The issue still exists in 1.5.6
Started to appear again at the end of last week when a new supplementary update for Catalina arrived (10.15.4). I still had that test build you shared, but today updated to 1.5.6 and the issue appeared after switch from day to night theme as well.

<img width="125" alt="Screenshot 2020-04-13 at 20 52 53" src="https://user-images.githubusercontent.com/13467769/79145478-684d0d00-7dc9-11ea-9f34-e2e3aa2d3198.png">
